name = "openapi-condenser"
main = "src/backend/worker.ts"
compatibility_date = "2025-06-08"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[site]
bucket = "./dist"

[build]
command = "npm run build"